repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-symlinks
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-json
  - id: check-added-large-files
  - id: check-yaml
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: shfmt
#   - id: circleci-config-validate
#   - id: forbid-binary
#   - id: go-fmt
#   - id: go-test
#   - id: go-mod-tidy
#   - id: go-generate
#   - id: shellcheck
#   - id: shfmt
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.0.0
#   hooks:
#   - id: codespell
# - repo: https://github.com/adrienverge/yamllint.git
#   rev: v1.25.0
#   hooks:
#   - id: yamllint
#     files: \.(yaml|yml)$
#     types: [file, yaml]
#     entry: yamllint --strict
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.45.0
#   hooks:
#   - id: terraform_fmt
#     files: '\.tf$'
# - repo: local
#   hooks:
#   - id: go-fmt
#     name: go fmt
#     entry: ./scripts/go-fmt.sh
#     files: '\.go$'
#     language: script
#   - id: go-vet
#     name: go vet
#     entry: ./scripts/go-vet.sh
#     files: '\.go$'
#     language: script
#   - id: go-imports
#     name: go imports
#     entry: ./scripts/go-imports.sh
#     files: '\.go$'
#     language: script
