#!/usr/bin/env bash
#******************************************************************************

# Copyright 2015 Clark Hsu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#******************************************************************************
#echo "Begin: $(basename ${0})"
#set -e # Exit on error On
#set -x # Trace On
#******************************************************************************
# cp mysecrets_template ${HOME}/.mysecrets

# # Master Account
# MASTER_USER=
# MASTER_PASSWORD=
PASSWORD=

# Admin Account
if [ "${OS_ADMIN}" == "" ]; then
    OS_ADMIN="admin" # admin
fi
if [ "${OS_ADMIN_PASSWORD}" == "" ]; then
    OS_ADMIN_PASSWORD=
fi

# OS User Account
if [ "${USER_HOME}" == "" ]; then
    USER_HOME='/var/lib' # /home | /var/lib
fi
if [ "${OS_USER}" == "" ]; then
    OS_USER="tester" # tester
fi
if [ "${OS_USER_GROUP}" == "" ]; then
    OS_USER_GROUP="${OS_USER}" # tester
fi
if [ "${OS_USER_PASSWORD}" == "" ]; then
    OS_USER_PASSWORD=
fi
if [ "${OS_USER_EMAIL}" == "" ]; then
    OS_USER_EMAIL="${OS_USER}@localhost" # tester@localhost
fi

OS_USER_HOME="${USER_HOME}/${OS_USER}"    #
OS_USER_BIN="${USER_HOME}/${OS_USER}/bin" #

# # DB Admin Account
# if [ "${DB_ADMIN}" == "" ]; then
#     DB_ADMIN="root"                                   # root
# fi
# if [ "${DB_ADMIN_PASSWORD}" == "" ]; then
#     DB_ADMIN_PASSWORD=
# fi

# # DB User Account
# #if [ "${DB_NAME}" == "" ]; then
# #    DB_NAME="test_db"                                # mysql | test_db
# #fi
# if [ "${DB_USER}" == "" ]; then
#     DB_USER="tester"                                  # tester
# fi
# if [ "${DB_USER_PASSWORD}" == "" ]; then
#     DB_USER_PASSWORD==
# fi

# GitHub Account
if [ "${GITHUB_TEAM}" == "" ]; then
    GITHUB_TEAM=
fi
if [ "${GITHUB_USER}" == "" ]; then
    GITHUB_USER=tester
fi
if [ "${GITHUB_USER_PASSWORD}" == "" ]; then
    GITHUB_USER_PASSWORD=
fi
if [ "${GITHUB_USER_TOKEN}" == "" ]; then
    # https://github.com/settings/tokens
    GITHUB_USER_TOKEN=
fi
if [ "${GITHUB_USER_EMAIL}" == "" ]; then
    GITHUB_USER_EMAIL=tester@example.com
fi

# # GitLab Account
# if [ "${GITLAB_TEAM}" == "" ]; then
#     GITLAB_TEAM=
# fi
# if [ "${GITLAB_USER}" == "" ]; then
#     GITLAB_USER=tester
# fi
# if [ "${GITLAB_USER_PASSWORD}" == "" ]; then
#     GITLAB_USER_PASSWORD=
# fi
# if [ "${GITLAB_USER_EMAIL}" == "" ]; then
#     GITLAB_USER_EMAIL=tester@example.com
# fi

# # BitBucket/Jira/Confluence Account
# if [ "${BITBUCKET_TEAM}" == "" ]; then
#     BITBUCKET_TEAM=
# fi
# if [ "${BITBUCKET_USER}" == "" ]; then
#     BITBUCKET_USER=tester
# fi
# if [ "${BITBUCKET_USER_PASSWORD}" == "" ]; then
#     BITBUCKET_USER_PASSWORD=
# fi
# if [ "${BITBUCKET_USER_EMAIL}" == "" ]; then
#     BITBUCKET_USER_EMAIL=tester@example.com
# fi

# Docker
if [ "${DOCKER_USER}" == "" ]; then
    DOCKER_USER=tester
fi
if [ "${DOCKER_PASSWORD}" == "" ]; then
    DOCKER_PASSWORD=
fi

# # AWS
# if [ "${AWS_ACCESS_KEY_ID}" == "" ]; then
#     AWS_ACCESS_KEY_ID="<id>"
# fi
# if [ "${AWS_SECRET_ACCESS_KEY}" == "" ]; then
#     AWS_SECRET_ACCESS_KEY="<key>"
# fi
# if [ "${AWS_DEFAULT_REGION}" == "" ]; then
#     AWS_DEFAULT_REGION="<region>"
# fi

# # Openstack
# if [ "${}" == "" ]; then
#     :
# fi
# if [ "${}" == "" ]; then
#     :
# fi
# if [ "${}" == "" ]; then
#     :
# fi

# IBS
if [ "${IBS_USERNAME}" == "" ]; then
    IBS_USERNAME=tester
    # IBS_USERNAME=$(osc config https://api.suse.de user | awk '$0=$NF' | tr -d "'")
fi
if [ "${IBS_PASSWORD}" == "" ]; then
    IBS_PASSWORD=
fi

# OBS
if [ "${OBS_USERNAME}" == "" ]; then
    OBS_USERNAME=tester
    # IBS_USERNAME=$(osc config https://api.opensuse.org user | awk '$0=$NF' | tr -d "'")
fi
if [ "${OBS_USERNAME}" == "" ]; then
    OBS_USERNAME=
fi

#******************************************************************************
#set +e # Exit on error Off
#set +x # Trace Off
#echo "End: $(basename ${0})"
#******************************************************************************
