apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-conf-server
  # namespace: kube-system
  namespace: default
  # labels:
  #   app: helloworld-server
data:
  helloworld.conf: |
    #### helloworld.conf ####

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-d-server
  # namespace: kube-system
  namespace: default
  # labels:
  #   app: helloworld-server
data:
  helloworld.conf: |
    #### helloworld.conf ####
