apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-server
  # namespace: kube-system
  namespace: default
  labels:
    app: helloworld-server
    # version: v1
    # kubernetes.io/cluster-service: "true"
spec:
  # minReadySeconds: 30
  # updateStrategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 2
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-server
      # version: v1
      # kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: helloworld-server
        # version: v1
        # kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: helloworld-server
      # priorityClassName: system-node-critical
      containers:
      - name: helloworld-server
        image: cclhsu/alpine_helloworld:latest
        # image: registry.suse.de/home/cclhsu/branches/devel/caasp/4.5/containers/containers/caasp/v4.5/helloworld:beta
        imagePullPolicy: Always
        # command: [ "helloworld" ]
        # args: [ "-n", "-f", "/etc/helloworld.conf" ]
        # command: [ "helloworld", "-n", "-f", "/etc/helloworld.conf" ]
        # securityContext:
        #   allowPrivilegeEscalation: true
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HELLOWORLD_PORT
          value: "514"
        - name: HELLOWORLD_PROTOCOL
          value: "tcp"
          # value: "udp"
        ports:
        - containerPort: 514
          name: tcp
          protocol: TCP
        - containerPort: 514
          name: udp
          protocol: UDP
        volumeMounts:
        - name: certs-volume
          mountPath: /etc/certs
          readOnly: true
        - name: helloworld-conf-volume
          mountPath: /etc/helloworld.conf
          subPath: helloworld.conf
          readOnly: true
        - name: helloworld-d-volume
          mountPath: /etc/helloworld.d
        # - name: host-var-log
        #   mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs-volume
        secret:
          secretName: certs-server
      - name: helloworld-conf-volume
        configMap:
          name: helloworld-conf-server
      - name: helloworld-d-volume
        configMap:
          name: helloworld-d-server
      # - name: host-var-log
      #   hostPath:
      #     path: /var/log
