apiVersion: v1
kind: Service
metadata:
  name: helloworld-server-service
  # namespace: kube-system
  namespace: default
  labels:
    app: helloworld-server
spec:
  selector:
    app: helloworld-server
  ports:
  - name: tcp-syslog
    port: 514
    targetPort: 514
    protocol: TCP
  - name: udp-syslog
    port: 514
    targetPort: 514
    protocol: UDP
  type: NodePort
