apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helloworld-server
  # labels:
  #   app: helloworld-server
  #   kubernetes.io/cluster-service: "true"
  #   addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: helloworld-server
  # namespace: kube-system
  namespace: default
- kind: Group
  name: system:nodes
roleRef:
  kind: ClusterRole
  name: helloworld-server
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helloworld-server-psp
  # labels:
  #   app: helloworld-server
  #   kubernetes.io/cluster-service: "true"
  #   addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: helloworld-server
  # namespace: kube-system
  namespace: default
- kind: Group
  name: system:nodes
roleRef:
  kind: ClusterRole
  name: cluster-admin
  # name: suse:caasp:psp:privileged
  apiGroup: rbac.authorization.k8s.io
