apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworld-server
  # labels:
  #   app: helloworld-server
  #   kubernetes.io/cluster-service: "true"
rules:
- apiGroups:
  - ""
  resources:
  - api
  - namespaces
  - nodes
  - pods
  # - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
# - apiGroups:
#   - extensions
#   resources:
#   - podsecuritypolicies
#   resourceNames:
#   - helloworld-server
#   verbs:
#   - use
