piVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: helloworld-server
  # labels:
  #   app: helloworld-server
  #   kubernetes.io/cluster-service: "true"
spec:
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    fsGroup:
      rule: RunAsAny
    volumes:
      - 'configMap'
      - 'secret'
      - 'hostPath'
    privileged: false
    allowedHostPaths:
      - pathPrefix: /var/lib
        readOnly: false
      - pathPrefix: /var/log
        readOnly: true
      - pathPrefix: /etc
        readOnly: true
      - pathPrefix: /run
        readOnly: true
