# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/engine/reference/commandline/cli/
# https://docs.docker.com/compose/compose-file/compose-versioning/
# https://docs.docker.com/engine/reference/commandline/volume_create
version: '3.9'
# volumes:
#   alpine-template-etc-volume: {}
#   alpine-template-var-volume: {}
#   # alpine-template-tmp-volume: {}
networks:
  alpine_template_network: {}
services:
  alpine_template:
    # build: .
    image: alpine_base/alpine_template:latest
    container_name: alpine_template
    # restart: always
    hostname: alpine_template
    # env_file:
    #   - env_file/alpine_template.env
    environment:
      # PATH: /app:$PATH
      # PYTHONPATH: /app:$PYTHONPATH
      MODE: default
      START_ARGS: /bin/bash
    # command: python test.py
    ports:
      - 22:22
      - 80:80
      - 443:443
      - 873:873
      - 127.0.0.1:1110:1110
    # labels:
    #   alpine_template.cluster: "alpine_template"
    volumes:
      - ./app:/project/app
      - ./appfs/data:/project/data
      # - ./appfs/logs:/project/logs
      # - ./src:/project/src
      # - ./tests:/project/tests
      # - ./rootfs/default:/etc/default
      # - ./rootfs/etc:/etc/app
      # - ./rootfs/var:/opt/app/var
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - alpine-template-etc-volume:/etc/app
      # - alpine-template-var-volume:/opt/app/var
      # - alpine-template-var-volume:/opt/app/tmp
    # networks:
    #   alpine_template_network:
    #     aliases:
    #       - alpine_template
    # restart: always
    # entrypoint: /bin/bash
    # stdin_open: true
    # tty: true
    # depends_on:
    #   - zookeeper
    #   - kafka
